// Code generated by go-gen-dapr. DO NOT EDIT.
// version: v0.2.0
// source:  github.com/purefun/go-gen-dapr/examples/pubsub

package pubsub

import (
	"context"
	"encoding/json"
	"github.com/dapr/go-sdk/client"
)

type Pubsub struct {
	client     client.Client
	pubsubName string
}

func NewPubsub(c client.Client, name string) *Pubsub {
	return &Pubsub{client: c, pubsubName: name}
}

func (p *Pubsub) PublishUserRegisteredEvent(ctx context.Context, event UserRegisteredEvent) error {
	data, err := json.Marshal(event)
	if err != nil {
		return err
	}
	return p.client.PublishEvent(ctx, p.pubsubName, "UserRegisteredEvent", data)
}
