// Code generated by go-gen-dapr. DO NOT EDIT.
// version: v0.6.0
// source:  github.com/purefun/go-gen-dapr/examples/echo/service.Subscriptions

package service

import (
	"context"
	"encoding/json"
	"github.com/dapr/go-sdk/service/common"
	"github.com/purefun/go-gen-dapr/pkg/dapr"
	errorHandlers "github.com/purefun/go-gen-dapr/pkg/errors"
)

func _SendEmail_Handler(subscriber Subscriptions) dapr.TopicHandlerFunc {
	return func(ctx context.Context, e *common.TopicEvent) (retry bool, err error) {
		var event UserRegisteredEvent
		err = json.Unmarshal(e.Data.([]byte), &event)
		if err != nil {
			return false, err
		}
		return subscriber.SendEmail(ctx, event)
	}
}

func RegisterSubscriber(s common.Service, subscriber Subscriptions, pubsubName string) {
	s.AddTopicEventHandler(
		&common.Subscription{
			PubsubName: pubsubName,
			Topic:      "UserRegisteredEvent",
		},
		errorHandlers.SubscriberErrorHandler(_SendEmail_Handler(subscriber)),
	)
}
